### ISSUE TITLE
`neuro job logs` fails with aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-cli#2361]
#### Description:
This is a floating bug.
Unfortunately, I cannot provide cosine steps to reproduce it, but in the majority, it happens when:
1. I'm attached to the running job for reading the logs.
2. Logs appear in the job from time to time (once in, say, 10 minutes).
3. After some time, say, one hour, the CLI fails with the following traceback:

<details>
<summary> Traceback </summary>

```
ERROR: Connection error (Response payload is not completed)
Traceback (most recent call last):
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/neuro_cli/main.py", line 556, in main
    cli.main(**kwargs)
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/neuro_cli/utils.py", line 325, in invoke
    super().invoke(ctx)
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/neuro_cli/utils.py", line 288, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/neuro_cli/utils.py", line 102, in wrapper
    return root.run(
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/neuro_cli/root.py", line 174, in run
    return self._runner.run(main)
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/neuro_cli/asyncio_utils.py", line 55, in run
    return self._loop.run_until_complete(main_task)
  File "/Users/ysem/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/neuro_cli/utils.py", line 74, in _run_async_function
    return await func(root, *args, **kwargs)
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/neuro_cli/job.py", line 226, in logs
    await process_logs(
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/neuro_cli/ael.py", line 98, in process_logs
    async for chunk in it:
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/neuro_sdk/jobs.py", line 526, in monitor
    async for data in resp.content.iter_any():
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/aiohttp/streams.py", line 39, in __anext__
    rv = await self.read_func()
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/aiohttp/streams.py", line 392, in readany
    await self._wait("readany")
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/aiohttp/streams.py", line 306, in _wait
    await waiter
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
```

</details>

#### Additional context:
Neuro Platform Client 21.9.3
Python 3.8.5
aiohttp 3.7.4.post0
neuro-docker-local-public.jfrog.io/platformmonitoringapi:21.9.19 - no errors found in logs
cluster: `default`

**Comment by YevheniiSemendiak** [comment]
It still appears. @romasku, afair we write some logs to the `~/.neuro/logs/` folder? Might that help?
