### ISSUE TITLE
`make docs` fails

### ISSUE THREAD

**Issue by serhiy-storchaka** [neuro-inc/neuro-cli#2650]
```
$ make docs 
build-tools/cli-help-generator.py CLI.in.md CLI.md
Traceback (most recent call last):
  File "/home/serhiy/neuromation/platform-client-python/build-tools/cli-help-generator.py", line 210, in <module>
    main()
  File "/home/serhiy/neuromation/platform-client-python/build-tools/cli-help-generator.py", line 203, in main
    info = parse_command(None, cli, ["neuro"])
  File "/home/serhiy/neuromation/platform-client-python/build-tools/cli-help-generator.py", line 83, in parse_command
    parse_command(ctx, sub_cmd, stack + [command_name])
  File "/home/serhiy/neuromation/platform-client-python/build-tools/cli-help-generator.py", line 73, in parse_command
    info = parse_doc(ctx, command, stack)
  File "/home/serhiy/neuromation/platform-client-python/build-tools/cli-help-generator.py", line 44, in parse_doc
    command.format_help_text(ctx, formatter)
  File "/home/serhiy/neuromation/platform-client-python/neuro-cli/src/neuro_cli/utils.py", line 211, in format_help_text
    format_example(example, formatter)
  File "/home/serhiy/neuromation/platform-client-python/neuro-cli/src/neuro_cli/utils.py", line 152, in format_example
    formatter.write_text("\b\n" + " ".join(shlex.split(line)))
  File "/home/serhiy/.pyenv/versions/3.10.4/lib/python3.10/shlex.py", line 315, in split
    return list(lex)
  File "/home/serhiy/.pyenv/versions/3.10.4/lib/python3.10/shlex.py", line 300, in __next__
    token = self.get_token()
  File "/home/serhiy/.pyenv/versions/3.10.4/lib/python3.10/shlex.py", line 109, in get_token
    raw = self.read_token()
  File "/home/serhiy/.pyenv/versions/3.10.4/lib/python3.10/shlex.py", line 191, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation
make: *** [Makefile:115: docs] Помилка 1
```

Python 3.10.4, the newly created virtual environment.

**Comment by serhiy-storchaka** [comment]
That error can be fix by
```
diff --git a/neuro-cli/src/neuro_cli/utils.py b/neuro-cli/src/neuro_cli/utils.py
index edb0316c..15d0bf0f 100644
--- a/neuro-cli/src/neuro_cli/utils.py
+++ b/neuro-cli/src/neuro_cli/utils.py
@@ -144,7 +144,7 @@ def split_examples(help: str) -> List[str]:
 def format_example(example: str, formatter: click.HelpFormatter) -> None:
     with formatter.section(click.style("Examples", bold=True, underline=False)):
         for line in example.splitlines():
-            is_comment = line.startswith("#")
+            is_comment = line.lstrip().startswith("#")
             if is_comment:
                 formatter.write_text("\b\n" + click.style(line, dim=True))
             else:
```
It seems that some lines in generated `.md` files are now indented with 4 spaces.

**Comment by serhiy-storchaka** [comment]
Other error:
```
$ neuro cp --help
ERROR: No closing quotation
```

**Comment by serhiy-storchaka** [comment]
The `check-commands-docs` hook raises error:
```
Command 'neuro storage df' short help is longer then 45 characters
```
