### ISSUE TITLE
`mkcredentials` fails with TypeError: mkcredentials() got an unexpected keyword argument 'project'

### ISSUE THREAD

**Issue by andriihomiak** [neuro-inc/neuro-cli#2987]
#### Description:
Stack trace of `neuro blob mkcredentials`

```
Using selector: EpollSelector
Executing command ['/home/andrii/projects/neuro-cli/.venv/bin/neuro', 'blob', 'mkcredentials', 'doing-some-tests']
mkcredentials() got an unexpected keyword argument 'project'
Traceback (most recent call last):
  File "/home/andrii/projects/neuro-cli/neuro-cli/src/neuro_cli/main.py", line 557, in main
    cli.main(
  File "/home/andrii/projects/neuro-cli/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/andrii/projects/neuro-cli/neuro-cli/src/neuro_cli/utils.py", line 332, in invoke
    super().invoke(ctx)
  File "/home/andrii/projects/neuro-cli/.venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/andrii/projects/neuro-cli/neuro-cli/src/neuro_cli/utils.py", line 332, in invoke
    super().invoke(ctx)
  File "/home/andrii/projects/neuro-cli/.venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/andrii/projects/neuro-cli/neuro-cli/src/neuro_cli/utils.py", line 298, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/andrii/projects/neuro-cli/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/andrii/projects/neuro-cli/.venv/lib/python3.10/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/andrii/projects/neuro-cli/neuro-cli/src/neuro_cli/utils.py", line 110, in wrapper
    return root.run(
  File "/home/andrii/projects/neuro-cli/neuro-cli/src/neuro_cli/root.py", line 148, in run
    return self._runner.run(main)
  File "/home/andrii/projects/neuro-cli/neuro-cli/src/neuro_cli/asyncio_utils.py", line 53, in run
    return self._loop.run_until_complete(main_task)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/andrii/projects/neuro-cli/neuro-cli/src/neuro_cli/utils.py", line 82, in _run_async_function
    return await func(root, *args, **kwargs)
TypeError: mkcredentials() got an unexpected keyword argument 'project'
```

**Comment by andriihomiak** [comment]
closed by #2997
